Auto appdate
yuu0919/chat-space pull request #15
Opened 2019-01-11 11:40 UTC by yuu0919

#WHAT
メッセージの自動更新機能の実装

#WHY
メッセージを他のユーザーとリアルタイムで共有できるようにするため

2019-01-11 11:48 UTC, ghost requested changes

2019-01-11 11:48 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +      format.json { @new_message = Message.where('id > ?', params[:message][:id]) }
これだと別のグループのメッセージが追加されませんか？

2019-01-11 11:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    });
インデントずれてます

2019-01-11 11:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      console.log(data);
削除しましょう

2019-01-11 11:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    .always(function(data){
成功した時の.doneと失敗した時の処理も記述しましょう

2019-01-12 08:11 UTC, yuu0919 commented
message.jsに記述していたのをindex.jsに移してます。
自動更新した際、新しいメッセージがある時はスクロールするようにしました。

2019-01-12 08:15 UTC, kuroko918 commented
LGTMです！

2019-01-12 08:15 UTC, merged